plugins {
    id 'org.jetbrains.kotlin.jvm' version '2.3.0'
    id 'application'
    id("com.gradleup.shadow") version "9.3.1"
}

group = 'org.game'
version = '1.2.0'

repositories {
    mavenCentral()
}

dependencies {
    implementation platform("org.lwjgl:lwjgl-bom:3.4.1")

    implementation "org.lwjgl:lwjgl"
    implementation "org.lwjgl:lwjgl-glfw"
    implementation "org.lwjgl:lwjgl-opengl"
    implementation "org.lwjgl:lwjgl-stb"
    implementation 'org.joml:joml:1.10.8'
    implementation "org.lwjgl.lwjgl:lwjgl_util:2.9.3"
    implementation "org.lwjgl:lwjgl-openal"

    implementation "com.googlecode.soundlibs:mp3spi:1.9.5.4"
    implementation "com.googlecode.soundlibs:tritonus-share:0.3.7.4"

    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2"

    runtimeOnly "org.lwjgl:lwjgl::natives-linux"
    runtimeOnly "org.lwjgl:lwjgl-glfw::natives-linux"
    runtimeOnly "org.lwjgl:lwjgl-opengl::natives-linux"
    runtimeOnly "org.lwjgl:lwjgl-stb::natives-linux"
    runtimeOnly "org.lwjgl:lwjgl-openal::natives-linux"
    runtimeOnly "org.lwjgl:lwjgl::natives-windows"
    runtimeOnly "org.lwjgl:lwjgl-glfw::natives-windows"
    runtimeOnly "org.lwjgl:lwjgl-opengl::natives-windows"
    runtimeOnly "org.lwjgl:lwjgl-stb::natives-windows"
    runtimeOnly "org.lwjgl:lwjgl-openal::natives-windows"
    runtimeOnly "org.lwjgl:lwjgl::natives-macos"
    runtimeOnly "org.lwjgl:lwjgl-glfw::natives-macos"
    runtimeOnly "org.lwjgl:lwjgl-opengl::natives-macos"
    runtimeOnly "org.lwjgl:lwjgl-stb::natives-macos"
    runtimeOnly "org.lwjgl:lwjgl-openal::natives-macos"
    testImplementation 'org.jetbrains.kotlin:kotlin-test'
}

test {
    useJUnitPlatform()
}
kotlin {
    jvmToolchain(17)
}

application {
    mainClass = 'org.game.invaders.GameKt' // adjust to your main
    if (org.gradle.internal.os.OperatingSystem.current().isMacOsX()) {
        applicationDefaultJvmArgs = ["-XstartOnFirstThread"]
    }
}

jar {
    manifest {
        attributes 'Main-Class': application.mainClass
    }
    // Optionally:
    // duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.shadowJar {
    manifest { attributes["Main-Class"] = application.mainClass.get() }
}
